language: objective-c
osx_image: xcode8.3
branches:
  only:
    - master
env:
  global:
    - IOS_SCHEME="SimpleJson iOS"
    - TVOS_SCHEME="SimpleJson tvOS"
    - MACOS_SCHEME="SimpleJson macOS"
    - WATCHOS_SCHEME="SimpleJson watchOS"
  matrix:
    - ACTION="TEST"
      SCHEME="$IOS_SCHEME"
      DESTINATION="OS=10.3.1,name=iPhone 6s"
    - ACTION="TEST"
      SCHEME="$TVOS_SCHEME"
      DESTINATION="OS=10.2,name=Apple TV 1080p"
    - ACTION="TEST"
      SCHEME="$MACOS_SCHEME"
      DESTINATION="arch=x86_64"
    - ACTION="BUILD"
      SCHEME="$WATCHOS_SCHEME"
      DESTINATION="OS=3.2,name=Apple Watch - 42mm"
script:
  - if [ $ACTION == "TEST" ]; then
      xcodebuild -project SimpleJson.xcodeproj -scheme "$SCHEME" -destination "$DESTINATION" clean test | xcpretty;
    else
      xcodebuild -project SimpleJson.xcodeproj -scheme "$SCHEME" -destination "$DESTINATION" clean build | xcpretty;
    fi
